apiVersion: v1
kind: Secret
metadata:
  name: phonebill-common-secret
  namespace: phonebill
  labels:
    app.kubernetes.io/part-of: phonebill
type: Opaque
stringData:
  # JWT Secret (최소 256비트 이상, HS256 알고리즘용)
  JWT_SECRET: "EK1ZV7vROOXREXbYe/BCISdQq0Yklk9JtoA2v88ux1DBDc0bDGiRRxHeDSb7GHkDP9IUYHMVsBi4/1rS4OhfRg=="
  # Redis 비밀번호 (비밀번호 없는 경우 빈 값)
  REDIS_PASSWORD: "P@ssw0rd$"
