apiVersion: v1
kind: Secret
metadata:
  name: phonebill
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "docker.io": {
          "username": "${DOCKER_USERNAME}",
          "password": "${DOCKER_PASSWORD}",
          "auth": "${DOCKER_AUTH}"
        }
      }
    }