apiVersion: apps/v1
kind: Deployment
metadata:
  name: kos-mock
  namespace: phonebill
  labels:
    app: kos-mock
    app.kubernetes.io/part-of: phonebill
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kos-mock
  template:
    metadata:
      labels:
        app: kos-mock
    spec:
      containers:
      - name: kos-mock
        image: docker.io/hiondal/kos-mock:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
          name: http
        envFrom:
        - configMapRef:
            name: phonebill-common-config
        - configMapRef:
            name: kos-mock-config
        - secretRef:
            name: phonebill-common-secret
        resources:
          requests:
            cpu: "256m"
            memory: "256Mi"
          limits:
            cpu: "1024m"
            memory: "1024Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8084
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
