apiVersion: v1
kind: ConfigMap
metadata:
  name: phonebill-common-config
  
  labels:
    app.kubernetes.io/part-of: phonebill
data:
  SPRING_PROFILES_ACTIVE: "prod"
  REDIS_HOST: "cache-redis-master"
  REDIS_PORT: "6379"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://phonebill.72.155.72.236.nip.io"
  SHOW_SQL: "false"
  DDL_AUTO: "none"
