apiVersion: v1
kind: Secret
metadata:
  name: user-service-db-secret
  labels:
    app: user-service
    app.kubernetes.io/part-of: phonebill
type: Opaque
stringData:
  DB_USERNAME: "unicorn"
  DB_PASSWORD: "PROD_DB_PASSWORD"
