apiVersion: v1
kind: Service
metadata:
  name: kos-mock
  namespace: phonebill
  labels:
    app: kos-mock
    app.kubernetes.io/part-of: phonebill
spec:
  type: ClusterIP
  selector:
    app: kos-mock
  ports:
  - name: http
    port: 8084
    targetPort: 8084
    protocol: TCP
