apiVersion: v1
kind: Secret
metadata:
  name: phonebill-common-secret
  labels:
    app.kubernetes.io/part-of: phonebill
type: Opaque
stringData:
  JWT_SECRET: "EK1ZV7vROOXREXbYe/BCISdQq0Yklk9JtoA2v88ux1DBDc0bDGiRRxHeDSb7GHkDP9IUYHMVsBi4/1rS4OhfRg=="
  REDIS_PASSWORD: "P@ssw0rd$"
