apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill-service
  labels:
    app: bill-service
    app.kubernetes.io/part-of: phonebill
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bill-service
  template:
    metadata:
      labels:
        app: bill-service
    spec:
      containers:
      - name: bill-service
        image: docker.io/hiondal/bill-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
          name: http
        envFrom:
        - configMapRef:
            name: cm-common
        - configMapRef:
            name: cm-bill-service
        - secretRef:
            name: secret-common
        - secretRef:
            name: secret-bill-service
        resources:
          requests:
            cpu: "256m"
            memory: "256Mi"
          limits:
            cpu: "1024m"
            memory: "1024Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
