apiVersion: v1
kind: Secret
metadata:
  name: bill-service-db-secret
  
  labels:
    app: bill-service
    app.kubernetes.io/part-of: phonebill
type: Opaque
stringData:
  DB_USERNAME: "unicorn"
  DB_PASSWORD: "P@ssw0rd$"
