apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: phonebill
  labels:
    app: product-service
    app.kubernetes.io/part-of: phonebill
data:
  SERVER_PORT: "8083"
  DB_HOST: "change-postgresql"
  DB_PORT: "5432"
  DB_NAME: "changedb"
  REDIS_DATABASE: "2"
  KOS_BASE_URL: "http://kos-mock:8084"
  DDL_AUTO: "update"
